version: "2"
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "9000:9000"
    env_file:
      - .env

volumes:
  node_modules:
