version: "2.4"
services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=14253678
      - POSTGRES_DB=st_db
    ports:
      - "5432:5432"

  backend:
    image: cpenaforte/st-back-test:latest
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - NODE_ENV=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=14253678
      - POSTGRES_DB=st_db
      - HOSTNAME=postgres
      - DB_PORT=5432
      - SALT_ROUNDS=10
      - TOKEN_KEY=simpleTasks
    depends_on:
      - postgres
    ports:
      - "3000:3000"